<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ConceptualSectionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $inserts = array(
            [ 'conceptual_section' => 'La comunicación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Situaciones comunicativas. Los usos lingüisticos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Técnicas de interacción grupal', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La exposición oral', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La lectura: propósitos y tipos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El texto legal', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El texto expositivo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El texto informativo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La narración', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La descripción', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La argumentación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Las instrucciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Aspectos formales de la lengua escrita', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Técnicas de comprensión de la lectura', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Bosquejos y esquemas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El libro y sus partes', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Tipos de libros', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El trabajo de investigación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El resumen. Ideas principales y secundarias', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El subrayado y la toma de notas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Elaboración de informes', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Formulación de preguntas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La ficha biográfica', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La ficha bibliográfica', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La biblioteca', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El significado de las palabras', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El diccionario', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La oración y sus partes. Ampliación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El párrafo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La familia de palabras', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Procesos de formación de palabras', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Sustitución de palabras. La elipsis', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Los conectores', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La tilder. Palabras agudas, graves y esdrújulas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La tilde en diptongos e hiatos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La tilde diacrítica', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El punto', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La coma', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El guión largo. El paréntesis', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Uso de la b', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Uso de la s', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Uso de la ll y la y', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Función poética del lenguaje', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Los recursos literarios', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La fábula', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La leyenda', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El mito', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Copla y décima', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El teatro. El texto teatral', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Prosa y verso', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El poema', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Clasificación de poemas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El cuento', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El lenguaje publicitario', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La campaña publicitaria', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Publicaciones periódicas. Su estructura formal', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El contenido del periódico', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'La radio, la televisión y el cine', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Otros medios de comunicación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'El lenguaje no verbal', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],
            [ 'conceptual_section' => 'Señales y símbolos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 1 ],

            [ 'conceptual_section' => 'Sistema de numeración', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Sistema de numeración binario y quinario', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Sistema de numeración decimal', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Descomposición de números naturales y decimales', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Orden de los números naturales y decimales', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Aproximación y redondeo de números decimales', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Números negativos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Orden de los números negativos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Operaciones combinadas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Propiedades de la adición y de la multiplicación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Potenciación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Uso de las potencias', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Comparación de potencias', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Radicación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Criterios de divisibilidad', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Mínimo común múltiplo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Máximo común divisor', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Propiedades y usos del m.c.m. y m.c.d.', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Uso del m.c.d. en la simplificación de fracciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Orden de las fracciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Adición y sustracción con fracciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Multiplicación con fracciones y propiedades', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'División de fracciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Ecuaciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Ecuaciones equivalentes', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Solución de una ecuación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Solución de una situación por medio de ecuaciones', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Proporcionalidad', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Regla de tres directa e inversa', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Porcentaje e interés simple', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Circunferencia inscrita en un polígono', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Construcción de cuadriláteros', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Mediatrices de un triángulo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Bisectrices de los ángulos internos de un triángulo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Medianas de un triángulo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Alturas de un triángulo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Cuerpos geométricos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Construcción de cuerpos geométricos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Congruencia', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Simetrías', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Medidas de tiempo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Longitud de una circunferencia', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Medidas de superficie', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Área de polígonos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Área del círculo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Área de figuras planas irregulares', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Volumen', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Medidas de volumen', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Relación entre capacidad y volumen', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Volumen de un paralelepípedo recto', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Tabla de frecuencias', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Media aritmética y mediana', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Diagrama de barras y de líneas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Histograma', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Diagrama circular', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Diagrama de árbol', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],
            [ 'conceptual_section' => 'Probabilidad y azar', 'created_at' => Carbon::now(), 'knowledge_area_id' => 2 ],

            [ 'conceptual_section' => 'Masa, volumen y densidad de los materiales', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Las mezclas y su clasificación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Sustancias puras: simples y compuestas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La luz y los fenómenos luminosos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'El sonido', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La Tierra y sus movimientos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La geósfera', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La hidrósgera', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La atmósfera', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La biósfera y los ecosistemas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La tecnósfera', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Recursos naturales renovables y no renovables', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Impacto ambiental', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Fuentes alternativas de energía', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'El estado nutricional y la alimentación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Problemas de salud pública', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Infecciones de transmisión sexual y su prevención', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Proyecto de vida', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Eventos socionaturales', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La computadora', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'La electricidad', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Los circuitos eléctricos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],
            [ 'conceptual_section' => 'Los motores', 'created_at' => Carbon::now(), 'knowledge_area_id' => 3 ],

            [ 'conceptual_section' => 'Diversidad cultural venezolana', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'La democracia', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Nuestra constitución', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Deberes y derechos ciudadanos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Los derechos humanos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Poder Público Nacional', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Poder Público Estadal y Municipal', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'El presupuesto nacional', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Nuestros símbolos patrios', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'El ideario bolivariano', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Sociedad bolivariana', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Las necesidades básicas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Distribución de la población venezolana', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'La población y los sectores de la economía', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'El paisaje rural', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'El paisaje urbano-industrial', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'La centralización político-administrativa', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Los desequilibrios espaciales', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Los problemas fronterizos', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Venezuela y América Latina', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Fuentes para la construcción de la historia', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Del telégrafo a la comunicación vía satélite', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'La economía en la Venezuela agraría', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Acontecimientos del siglo XIX', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Presidentes del siglo XIX a partir de 1860', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'La aparición del petróleo', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Un vistazo al siglo XX', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'Presidentes del siglo XX hasta 1958', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],
            [ 'conceptual_section' => 'La Venezuela contemporánea', 'created_at' => Carbon::now(), 'knowledge_area_id' => 4 ],

            [ 'conceptual_section' => 'Expresión en las artes plásticas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'La forma en las artes plásticas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'El ritmo en las expresiones artísticas', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'El lenguaje, el estilo y el género musical', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'La voz y el canto', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'La notación musical', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'El diseño gráfico', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'El dibujo técnico en el diseño industrial', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ],
            [ 'conceptual_section' => 'El patrimonio de la nación', 'created_at' => Carbon::now(), 'knowledge_area_id' => 5 ]
        );
        DB::table('conceptual_sections')->insert($inserts);
    }
}
