<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class GroupsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $inserts = array(
            ['student_id' => 1, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 2, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 3, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 4, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 5, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 6, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 7, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 8, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 9, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 10, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 11, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 12, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 13, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 14, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 15, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 16, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 17, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 18, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 19, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 20, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 21, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 22, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 23, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 24, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 25, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 26, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 27, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 28, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 29, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 30, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 31, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 32, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 33, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 34, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 35, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 36, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 37, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 38, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 39, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 40, 'course_id' => 1, 'created_at' => Carbon::now()],
            ['student_id' => 41, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 42, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 43, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 44, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 45, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 46, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 47, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 48, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 49, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 50, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 51, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 52, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 53, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 54, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 55, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 56, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 57, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 58, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 59, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 60, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 61, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 62, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 63, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 64, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 65, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 66, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 67, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 68, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 69, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 70, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 71, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 72, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 73, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 74, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 75, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 76, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 77, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 78, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 79, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 80, 'course_id' => 2, 'created_at' => Carbon::now()],
            ['student_id' => 81, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 82, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 83, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 84, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 85, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 86, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 87, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 88, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 89, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 90, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 91, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 92, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 93, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 94, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 95, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 96, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 97, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 98, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 99, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 100, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 101, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 102, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 103, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 104, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 105, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 106, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 107, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 108, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 109, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 110, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 111, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 112, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 113, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 114, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 115, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 116, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 117, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 118, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 119, 'course_id' => 3, 'created_at' => Carbon::now()],
            ['student_id' => 120, 'course_id' => 3, 'created_at' => Carbon::now()],
        );
        DB::table('groups')->insert($inserts);
    }
}
