<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use App\Evaluation;

class QualificationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        $evaluations = Evaluation::all();

        foreach ($evaluations as $evaluation) {
            $students = $evaluation->course->students;

            if ( 91 > $evaluation->id ) {
                if ( Carbon::now()->gt($evaluation->start_date) ) {
                    foreach ($students as $student) {
                        $evaluation->students()->syncWithoutDetaching([$student->id => ['qualification' => $faker->numberBetween($min = 5, $max = 20)]]);
                    }
                }
            }
        }

        $evaluation = Evaluation::findOrFail(91);
        $evaluation->students()->syncWithoutDetaching([
            121 => ['qualification' => '10' ],
            123 => ['qualification' => '09' ],
            124 => ['qualification' => '09' ],
            125 => ['qualification' => '03' ],
            126 => ['qualification' => '17' ],
            130 => ['qualification' => '05' ],
            131 => ['qualification' => '04' ],
            132 => ['qualification' => '10' ],
            133 => ['qualification' => '11' ],
            134 => ['qualification' => '07' ],
            135 => ['qualification' => '08' ],
            136 => ['qualification' => '05' ],
            137 => ['qualification' => '03' ],
            138 => ['qualification' => '01' ],
            139 => ['qualification' => '12' ],
            140 => ['qualification' => '11' ],
            141 => ['qualification' => '17' ],
            142 => ['qualification' => '10' ],
            143 => ['qualification' => '09' ],
            144 => ['qualification' => '04' ],
            145 => ['qualification' => '00' ],
            146 => ['qualification' => '09' ],
            147 => ['qualification' => '06' ],
            148 => ['qualification' => '04' ],
            149 => ['qualification' => '03' ],
            150 => ['qualification' => '03' ],
            151 => ['qualification' => '07' ],
            152 => ['qualification' => '11' ],
            153 => ['qualification' => '13' ],
            154 => ['qualification' => '03' ],
            155 => ['qualification' => '15' ],
            156 => ['qualification' => '00' ],
            157 => ['qualification' => '09' ],
            158 => ['qualification' => '12' ],
            159 => ['qualification' => '07' ],
            160 => ['qualification' => '09' ],
            161 => ['qualification' => '09' ],
            162 => ['qualification' => '10' ],
            164 => ['qualification' => '12' ],
            166 => ['qualification' => '14' ],
            167 => ['qualification' => '06' ],
            168 => ['qualification' => '12' ],
            169 => ['qualification' => '09' ],
            170 => ['qualification' => '00' ],
            171 => ['qualification' => '15' ]
        ]);

        $evaluation = Evaluation::findOrFail(92);
        $evaluation->students()->syncWithoutDetaching([
            121 => ['qualification' => '14' ],
            123 => ['qualification' => '09' ],
            124 => ['qualification' => '04' ],
            125 => ['qualification' => '00' ],
            126 => ['qualification' => '15' ],
            130 => ['qualification' => '09' ],
            132 => ['qualification' => '04' ],
            133 => ['qualification' => '12' ],
            134 => ['qualification' => '06' ],
            135 => ['qualification' => '02' ],
            136 => ['qualification' => '00' ],
            137 => ['qualification' => '03' ],
            138 => ['qualification' => '00' ],
            139 => ['qualification' => '06' ],
            140 => ['qualification' => '17' ],
            141 => ['qualification' => '20' ],
            142 => ['qualification' => '19' ],
            143 => ['qualification' => '03' ],
            145 => ['qualification' => '00' ],
            146 => ['qualification' => '01' ],
            147 => ['qualification' => '03' ],
            149 => ['qualification' => '02' ],
            150 => ['qualification' => '00' ],
            151 => ['qualification' => '13' ],
            152 => ['qualification' => '09' ],
            153 => ['qualification' => '10' ],
            155 => ['qualification' => '09' ],
            157 => ['qualification' => '11' ],
            158 => ['qualification' => '12' ],
            159 => ['qualification' => '03' ],
            160 => ['qualification' => '12' ],
            161 => ['qualification' => '02' ],
            162 => ['qualification' => '03' ],
            163 => ['qualification' => '06' ],
            164 => ['qualification' => '14' ],
            165 => ['qualification' => '04' ],
            166 => ['qualification' => '14' ],
            167 => ['qualification' => '05' ],
            168 => ['qualification' => '10' ],
            171 => ['qualification' => '11' ]
        ]);

        $evaluation = Evaluation::findOrFail(93);
        $evaluation->students()->syncWithoutDetaching([
            121 => ['qualification' => '12'],
            122 => ['qualification' => '05'],
            123 => ['qualification' => '08'],
            124 => ['qualification' => '16'],
            125 => ['qualification' => '06'],
            126 => ['qualification' => '16'],
            128 => ['qualification' => '13'],
            130 => ['qualification' => '15'],
            131 => ['qualification' => '00'],
            132 => ['qualification' => '13'],
            133 => ['qualification' => '14'],
            134 => ['qualification' => '19'],
            135 => ['qualification' => '06'],
            136 => ['qualification' => '06'],
            137 => ['qualification' => '10'],
            138 => ['qualification' => '09'],
            139 => ['qualification' => '18'],
            140 => ['qualification' => '17'],
            141 => ['qualification' => '19'],
            142 => ['qualification' => '20'],
            143 => ['qualification' => '16'],
            144 => ['qualification' => '04'],
            145 => ['qualification' => '09'],
            146 => ['qualification' => '11'],
            147 => ['qualification' => '10'],
            148 => ['qualification' => '09'],
            149 => ['qualification' => '15'],
            151 => ['qualification' => '18'],
            152 => ['qualification' => '15'],
            153 => ['qualification' => '20'],
            154 => ['qualification' => '10'],
            155 => ['qualification' => '11'],
            156 => ['qualification' => '04'],
            157 => ['qualification' => '13'],
            158 => ['qualification' => '20'],
            159 => ['qualification' => '15'],
            160 => ['qualification' => '17'],
            161 => ['qualification' => '14'],
            162 => ['qualification' => '09'],
            163 => ['qualification' => '09'],
            164 => ['qualification' => '18'],
            165 => ['qualification' => '16'],
            166 => ['qualification' => '19'],
            167 => ['qualification' => '11'],
            168 => ['qualification' => '16'],
            169 => ['qualification' => '03'],
            170 => ['qualification' => '08'],
            171 => ['qualification' => '10']
        ]);

        $evaluation = Evaluation::findOrFail(94);
        $evaluation->students()->syncWithoutDetaching([
            121 => ['qualification' => '15'],
            123 => ['qualification' => '08'],
            124 => ['qualification' => '17'],
            125 => ['qualification' => '03'],
            126 => ['qualification' => '17'],
            130 => ['qualification' => '16'],
            131 => ['qualification' => '07'],
            132 => ['qualification' => '09'],
            133 => ['qualification' => '16'],
            134 => ['qualification' => '15'],
            135 => ['qualification' => '12'],
            136 => ['qualification' => '07'],
            137 => ['qualification' => '05'],
            138 => ['qualification' => '18'],
            139 => ['qualification' => '17'],
            140 => ['qualification' => '16'],
            141 => ['qualification' => '17'],
            142 => ['qualification' => '18'],
            143 => ['qualification' => '05'],
            144 => ['qualification' => '09'],
            145 => ['qualification' => '08'],
            146 => ['qualification' => '15'],
            147 => ['qualification' => '09'],
            148 => ['qualification' => '16'],
            149 => ['qualification' => '17'],
            150 => ['qualification' => '06'],
            151 => ['qualification' => '17'],
            152 => ['qualification' => '17'],
            153 => ['qualification' => '18'],
            154 => ['qualification' => '09'],
            155 => ['qualification' => '08'],
            157 => ['qualification' => '15'],
            158 => ['qualification' => '18'],
            159 => ['qualification' => '14'],
            160 => ['qualification' => '17'],
            161 => ['qualification' => '16'],
            162 => ['qualification' => '17'],
            163 => ['qualification' => '10'],
            164 => ['qualification' => '15'],
            165 => ['qualification' => '16'],
            166 => ['qualification' => '17'],
            167 => ['qualification' => '10'],
            168 => ['qualification' => '16'],
            171 => ['qualification' => '08']
        ]);

        $evaluation = Evaluation::findOrFail(95);
        $evaluation->students()->syncWithoutDetaching([
            121 => ['qualification' => '18'],
            122 => ['qualification' => '11'],
            123 => ['qualification' => '16'],
            124 => ['qualification' => '20'],
            125 => ['qualification' => '11'],
            126 => ['qualification' => '19'],
            128 => ['qualification' => '00'],
            129 => ['qualification' => '00'],
            130 => ['qualification' => '18'],
            131 => ['qualification' => '11'],
            132 => ['qualification' => '17'],
            133 => ['qualification' => '18'],
            134 => ['qualification' => '18'],
            135 => ['qualification' => '07'],
            136 => ['qualification' => '16'],
            137 => ['qualification' => '11'],
            138 => ['qualification' => '10'],
            139 => ['qualification' => '17'],
            140 => ['qualification' => '19'],
            141 => ['qualification' => '19'],
            142 => ['qualification' => '19'],
            143 => ['qualification' => '13'],
            144 => ['qualification' => '09'],
            145 => ['qualification' => '12'],
            146 => ['qualification' => '16'],
            147 => ['qualification' => '13'],
            148 => ['qualification' => '13'],
            149 => ['qualification' => '17'],
            150 => ['qualification' => '03'],
            151 => ['qualification' => '19'],
            152 => ['qualification' => '11'],
            153 => ['qualification' => '18'],
            154 => ['qualification' => '09'],
            155 => ['qualification' => '03'],
            156 => ['qualification' => '07'],
            157 => ['qualification' => '14'],
            158 => ['qualification' => '19'],
            159 => ['qualification' => '16'],
            160 => ['qualification' => '17'],
            161 => ['qualification' => '14'],
            162 => ['qualification' => '13'],
            163 => ['qualification' => '12'],
            164 => ['qualification' => '19'],
            165 => ['qualification' => '15'],
            166 => ['qualification' => '16'],
            167 => ['qualification' => '14'],
            168 => ['qualification' => '20'],
            169 => ['qualification' => '02'],
            170 => ['qualification' => '05'],
            171 => ['qualification' => '17']
        ]);

        $evaluation = Evaluation::findOrFail(96);
        $evaluation->students()->syncWithoutDetaching([
            121 => ['qualification' => '17'],
            123 => ['qualification' => '17'],
            124 => ['qualification' => '20'],
            125 => ['qualification' => '00'],
            126 => ['qualification' => '18'],
            130 => ['qualification' => '20'],
            131 => ['qualification' => '03'],
            132 => ['qualification' => '15'],
            133 => ['qualification' => '20'],
            134 => ['qualification' => '18'],
            135 => ['qualification' => '10'],
            136 => ['qualification' => '07'],
            137 => ['qualification' => '15'],
            138 => ['qualification' => '15'],
            139 => ['qualification' => '19'],
            140 => ['qualification' => '19'],
            141 => ['qualification' => '19'],
            142 => ['qualification' => '20'],
            143 => ['qualification' => '01'],
            144 => ['qualification' => '00'],
            145 => ['qualification' => '17'],
            146 => ['qualification' => '14'],
            147 => ['qualification' => '15'],
            148 => ['qualification' => '11'],
            149 => ['qualification' => '16'],
            150 => ['qualification' => '00'],
            151 => ['qualification' => '19'],
            152 => ['qualification' => '20'],
            153 => ['qualification' => '18'],
            154 => ['qualification' => '01'],
            155 => ['qualification' => '03'],
            157 => ['qualification' => '16'],
            158 => ['qualification' => '17'],
            159 => ['qualification' => '09'],
            160 => ['qualification' => '19'],
            161 => ['qualification' => '13'],
            162 => ['qualification' => '17'],
            163 => ['qualification' => '07'],
            164 => ['qualification' => '19'],
            165 => ['qualification' => '15'],
            166 => ['qualification' => '16'],
            167 => ['qualification' => '16'],
            168 => ['qualification' => '18'],
            171 => ['qualification' => '20']
        ]);
    }
}
