<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class StudentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        factory(App\Student::class, 120)->create();

        $faker = Faker::create();

        $inserts = array(
            ['dni' => 27794819, 'second_name' => 'Altuve Briceño', 'name' => 'Leonardo Andrés', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27472711, 'second_name' => 'Andrade Andrade', 'name' => 'Joseanny Nathaly', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26838733, 'second_name' => 'Araque Pavón', 'name' => 'Ronald Alfonso', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27472251, 'second_name' => 'Caldera Monzon', 'name' => 'Diana Patricia', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26546740, 'second_name' => 'Carballo Casique', 'name' => 'Rosa Daimary', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27948326, 'second_name' => 'Castillo Aponte', 'name' => 'Luis Mario', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26989198, 'second_name' => 'Fernández Cárdenas', 'name' => 'Beatriz Elena', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26951517, 'second_name' => 'Gambera Zambrano', 'name' => 'Samuel Alejandro', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 28073728, 'second_name' => 'Garrido Hernández', 'name' => 'Johan Manuel', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26908270, 'second_name' => 'Gavidia Rodríguez', 'name' => 'Franco José', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26178353, 'second_name' => 'Gaviria Buesaquillo', 'name' => 'Francisco Javier', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26956067, 'second_name' => 'Gil Escalona', 'name' => 'Alfredo José', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27657650, 'second_name' => 'Gonzalez Iarussi', 'name' => 'Alessandra', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26995555, 'second_name' => 'Guzmán Ortiz', 'name' => 'Carlos Eduardo', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 28126839, 'second_name' => 'Hernández Sousa', 'name' => 'José Miguel', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27793099, 'second_name' => 'Landáez Carrero', 'name' => 'Lesmes Eliezer', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27741713, 'second_name' => 'León Hernández', 'name' => 'César Augusto', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27254279, 'second_name' => 'Macedo Madrid', 'name' => 'Andreina', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27006546, 'second_name' => 'Maldonado Landaeta', 'name' => 'Miguel Oswaldo', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 28007150, 'second_name' => 'Manilia Di Tommaso', 'name' => 'Francesco', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27187227, 'second_name' => 'Manzur Rueda', 'name' => 'Luisanna', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27235490, 'second_name' => 'Marín Paracuto', 'name' => 'Samuel Alberto', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 30456863, 'second_name' => 'Marques Rua De Abreu', 'name' => 'Gregory José', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 29553296, 'second_name' => 'Medina Acosta', 'name' => 'Freger Damián', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27916909, 'second_name' => 'Navas Godoy', 'name' => 'César Augusto', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27513628, 'second_name' => 'Oliveira Yndriago', 'name' => 'Samuel Alejandro', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26968964, 'second_name' => 'Ortega Ramirez', 'name' => 'Keiber René', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27377604, 'second_name' => 'Osuna Roa', 'name' => 'Karla Valentina', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27254402, 'second_name' => 'Pacheco Rodriguez', 'name' => 'Luis Carlos', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27342911, 'second_name' => 'Páez', 'name' => 'Antonio José', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27246338, 'second_name' => 'Páez Rodríguez', 'name' => 'Melanie De Las Nieves', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27588822, 'second_name' => 'Parra Azuaje', 'name' => 'Erick Antonio', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 28052148, 'second_name' => 'Perdomo Martinez', 'name' => 'Andrés Emilio', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27318573, 'second_name' => 'Pérez González', 'name' => 'Cristofer Aarón', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 28416865, 'second_name' => 'Pérez Hernández', 'name' => 'Leonardo Alfonso', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27660309, 'second_name' => 'Polanco Ayala', 'name' => 'Leonardo Alexander', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27448804, 'second_name' => 'Revollo Galviz', 'name' => 'Andrés Eloy', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 28218143, 'second_name' => 'Rivas González', 'name' => 'Ruth Hailerys', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27037275, 'second_name' => 'Rodríguez Carrillo', 'name' => 'Rafael Alberto', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27472244, 'second_name' => 'Rodríguez García', 'name' => 'Aschly Stecy', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27450089, 'second_name' => 'Romaite Carpio', 'name' => 'Hiram Shmuel', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27254168, 'second_name' => 'Romero Parra', 'name' => 'Fabiola Victoria', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27346113, 'second_name' => 'Rosello Grimaldo', 'name' => 'Rosa Mariella', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27235239, 'second_name' => 'Sánchez Piñerua', 'name' => 'Luis Enrique', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27784853, 'second_name' => 'Scott Molina', 'name' => 'Andrea Alejandra', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27038623, 'second_name' => 'Seijo Alarcón', 'name' => 'Andreina', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27622838, 'second_name' => 'Silva Khawam', 'name' => 'Fernando Elías', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 26989729, 'second_name' => 'Sucre Campíns', 'name' => 'Corina', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27421016, 'second_name' => 'Trujillo Fernandez', 'name' => 'Andrés Roberto', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27797887, 'second_name' => 'Villarroel Riobueno', 'name' => 'Dany Alejandro', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
            ['dni' => 27588099, 'second_name' => 'Zacarías Daboin', 'name' => 'David José', 'email' => $faker->unique()->userName . '@gmail.com', 'phone' => '0212' . $faker->randomNumber(7), 'mobile' => '0416' . $faker->randomNumber(7), 'address' => $faker->address, 'created_at' => Carbon::now() ],
        );
        DB::table('students')->insert($inserts);
    }
}
